<a href="https://colab.research.google.com/github/rejina0914/Worksheet/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1:Array creation
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np
arr1=np.empty((2,2))
print(arr1)

[[2.91323849e-315 0.00000000e+000]
 [5.73116149e-322 1.48419485e-071]]


In [ ]:
import numpy as np
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
arr3 = np.full((3,3),6)
print(arr3)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
arr4=np.zeros_like(array)
print(arr4)

[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
arr5=np.ones_like(array)
print(arr5)

[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
new_list=[1,2,3,4]
new_array=np.array(new_list)
print(new_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [ ]:
import numpy as np
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
arr1=np.arange(0,9).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
arr2 = np.eye(3,3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr3 = np.random.random(30)
print(arr3.mean())

0.38001748352180065


In [ ]:
import numpy as np
arr4 = np.random.random((10,10))
print("Minimum:",arr4.min())
print("Maximum:",arr4.max())

Minimum: 0.002939797411290357
Maximum: 0.9977250994974446


In [ ]:
import numpy as np
arr5 = np.zeros(10)
arr5[4] = 1
print(arr5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr6 = np.array([1,2,0,0,4,0])
print(arr6[::-1])


[0 4 0 0 2 1]


In [ ]:
import numpy as np
arr7 = np.ones((4,5))
arr7[1:-1, 1:-1] = 0
print(arr7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr8 = np.zeros((8,8))
arr8[1::2, ::2] = 1
arr8[::2, 1::2] = 1
print(arr8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.}
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("Addition of two arrays is:",np.add(x,y))
print("Subtraction of two array is:",np.subtract(x,y))
print("Multiplication of two arrays is:",v*4)
print("Square of each element is:",np.square(x))
print("Dot product of v and w is:",np.dot(v,w))
print("Dot product of x and v is:",np.dot(x,v))
print("Dot product of x and y is:",np.dot(x,y))
print("Concatenation of x and y along row is:",np.concatenate((x,y),axis=0))
print("Concatenation of x and v along column is:",np.vstack((x,v)))
print("Concatenation of x and v along column is:",np.concatenate((x,v),axis=1))


Addition of two arrays is: [[ 6  8]
 [10 13]]
Subtraction of two array is: [[-4 -4]
 [-4 -3]]
Multiplication of two arrays is: [36 40]
Square of each element is: [[ 1  4]
 [ 9 25]]
Dot product of v and w is: 219
Dot product of x and v is: [29 77]
Dot product of x and y is: [[19 22]
 [50 58]]
Concatenation of x and y along row is: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of x and v along column is: [[ 1  2]
 [ 3  5]
 [ 9 10]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The error occurs because all the input arrays must have same number of dimension.Here,'x' is a 2-dimensional array (shape (2, 2)) and 'v' is a 1-dimensional array (shape (2,)). NumPy's concatenate function requires that all arrays being concatenated have the same number of dimensions. You cannot directly concatenate arrays of different dimensions without reshaping one of them to match the other's dimensions.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT
.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#prove:A*A^-1=I
A1 = np.linalg.inv(A)
I = A.dot(A1)
I = np.round(I)
print("A*A^-1=I:\n",I)

#Prove: AB != BA
AB = A.dot(B)
BA = B.dot(A)
print("AB:\n",AB)
print("BA:\n",BA)
print("AB != BA")

#Prove (AB)^T = B^T A^T
left_side = AB.T
right_side = B.T.dot(A.T)
print(("(AB)^T:\n"),left_side)
print("B^T A^T:\n",right_side)
print("(AB)^T = B^T A^T")

#Linear equation using inverse method
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])
B = np.array([-1,-3,9])

print(np.dot(np.linalg.inv(A),B))

A*A^-1=I:
 [[1. 0.]
 [0. 1.]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T = B^T A^T
[ 2.  1. -2.]
